# Generated by Django 3.2.6 on 2021-10-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprestaurante', '0002_auto_20211003_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='slugc',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='slugp',
            new_name='slug',
        ),
    ]
